### ISSUE TITLE
Create Navigation.jsx

### ISSUE THREAD

**Issue by brunetsimon** [brunetsimon/live-poll#1]
Create a navigation for our App!

Requirement: We need an AppBar with a Title and at least 3 buttons.

- [ ] 1. A Client button which links to /client
- [ ] 2. A Server button which links to /server
- [ ] 3. An Admin button which links to /admin

Suggestion: Have a look here https://material-ui.com/demos/app-bar/ to find out how to use components like AppBar, Toolbar, Button, etc...

The link can be done using the "to" attribute described [here](https://reacttraining.com/react-router/web/example/basic)

You can test it here before pushing your changes (file Navigation.js) :
[![Edit material Ui basic example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vn7p4m1jo0)

**Comment by erikstroby** [comment]
vi tar dennn
