### ISSUE TITLE
Component to select which page to display

### ISSUE THREAD

**Issue by brunetsimon** [brunetsimon/live-poll#12]
You will be working in **Main.jsx**

This component is mainly a router with a [Switch](https://reacttraining.com/react-router/core/api/Switch), meaning that it will choose which page to display based on the URL we are at.

It shall do following:

- [ ] Display "Homepage" when the url path is exactly "/"
- [ ] Display "VotingClientSelector" when the url path is exactly "/client"
- [ ] Display "VotingClient" when the url path is "/client/:pollId"
- [ ] Display "VotingServerSelector" when the url path is exactly "/server"
- [ ] Display "VotingServer" when the url path is "/server/:pollId"

Note: :pollId means any ID. For example /client/1 the pollId is 1 and /client/IFG the pollId is IFG. This is how we know which poll the user would like to display.

You can test your implementation here:

[![Edit material Ui basic example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jn9kz8qzvw)

Don't forget to navigate to the correct URL!

**Comment by jonasenerback** [comment]
On it!
