### ISSUE TITLE
Make the page that display the graph result

### ISSUE THREAD

**Issue by brunetsimon** [brunetsimon/live-poll#16]
This task is to handle the page that will display the graph showing the total vote result.

It shall listen for changes in the database and update a graph every time a new vote is received.

It has thus two modules:

- [ ] A function that listen to the database update. 
- [ ] A bar graph (or other) displaying the result.
- [ ] Display the poll ID in the title available in the variable this.props.match.params.pollId

To implement the function listening to the database changes, look at [this part](https://firebase.google.com/docs/database/web/read-and-write#listen_for_value_events) of the documentation on how to continuously listen to value and update a local variable with the result. 
The snapshot value shall be stored locally in the state countArray.

The graph could be done using [this library](https://chartkick.com/react). Why not use the BarChart?

Before uploading your implementation you can test it here:
[![Edit material Ui basic example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7wr19pn98x)

**Comment by jonasenerback** [comment]
We take this!

**Comment by brunetsimon** [comment]
#24
