### ISSUE TITLE
Display the vote result

### ISSUE THREAD

**Issue by brunetsimon** [brunetsimon/live-poll#2]
Modify the file Result.jsx to display to the user which rating they selected and to inform that everything went well.

A sort of "thank you for voting. Here is your rating: Great".

Hints: 

- The rating is available in the variable _this.props.rating_ and correspond to a number. 
- The rating number meaning can be found in the file constant.js
- Have a look at the [material-ui library](https://material-ui.com/demos/paper/) to see how to insert components for formating

Before pushing your task, you can test it here in the file Result.jsx:
[![Edit material Ui basic example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5wm5j2wj04)

Note: You can change the value of the rating in the file App.js

**Comment by annikaca** [comment]
Taken by PAJ team

**Comment by annikaca** [comment]
Ready for Field Test
