### ISSUE TITLE
Display list of rating icons to vote

### ISSUE THREAD

**Issue by brunetsimon** [brunetsimon/live-poll#3]
The user votes by clicking on an smiley. 

This task is to create a list of all the icons so that the user can click on one of them to vote.

To do:

- [ ] Display all smiley icons used to vote. Hint, use[ IconButton and Icon](https://material-ui.com/demos/buttons/#icon-buttons).

- [ ] When the user click on the icon, the function this.props.callbackVote shall get the corresponding rating id. 

Hints: 

- The rating id, icon, name can be found in the file constant.js
- The callback function works as follow: this.props.callbackVote.bind(null, 3) for example to indicate that the user clicked on the icon with ID 3.
- Look at the [onClick](https://www.w3schools.com/jsref/event_onclick.asp) function to know how to detect a click from the user

Extra fun: Try to avoid to copy paste the same code for each icon. Have a look at the [map function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

You can test your code before pushing your task here in the file Vote.js:
[![Edit material Ui basic example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/503302ppjx)

**Comment by TeamTwoAsp** [comment]
Taken by Team ASP
