### ISSUE TITLE
Page which display either the voting or the result

### ISSUE THREAD

**Issue by brunetsimon** [brunetsimon/live-poll#4]
You will have to implement the VotingClient.jsx page.

This page has 2 functions:

- [ ] Display either the Result or Vote component depending if the user has voted or not
- [ ] Send the vote result to the firebase server

Hints:

- The variable that keep track if the user has voted is this.state.hasVoted
- The result component Result has one propertie "rating" which is the rating/vote number
- The vote component Vote has one propertie "callbackVote" which is the function that will handle the callback.
- The handleRatingCallback function shall take the rating and save it both in its internal state (this.setState) and in the database (see how to [push()](https://firebase.google.com/docs/database/web/lists-of-data) data to the database)
- The vote/rating shall be saved at the reference path "/polls/voteID/votes". 

You can test your code here (Not the push to firebase though... But that's a simple one :) )
[![Edit material Ui basic example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pxp90l28x)

**Comment by guddov** [comment]
We take it!
