### ISSUE TITLE
Page for user to choose a vote ID

### ISSUE THREAD

**Issue by brunetsimon** [brunetsimon/live-poll#6]
This task is to work with the file VotingClientSelector.jsx and VotingServerSelector.jsx

This file controls the page where the user has to enter which vote he/she wants to select. 

You need to implement the following features:

- [ ] A form for the user to enter the poll id. Use the [form](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Your_first_HTML_form) element and style it using [FormControl, Input, FormHelperText and Button](https://material-ui.com/demos/text-fields/#components).

- [ ] The form shall take the poll/vote Id and save it locally in this.state.pollId. Hint: Create an "onChange" function on the Input element. (Look at the source code examples [here](https://material-ui.com/demos/text-fields/#components).)

- [ ] When the user click the submit button the "handleSubmit" function will be called. It does 2 things: Check in the database if the pollId exists. If it does then navigate to the pollId URL (/client/ID or /server/ID) using [history.push](https://reacttraining.com/react-router/web/api/history). If it doesn't then display an error (this..state.errorMsg and this.state.showError)

You can test your code here before uploading it to Github.
[![Edit material Ui basic example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6x3oyxvq9z)

**Comment by adamjos** [comment]
We take this.
