### ISSUE TITLE
Add a homepage

### ISSUE THREAD

**Issue by brunetsimon** [brunetsimon/live-poll#8]
We need to add a homepage when the URL path is "/".

It could say something like welcome and then 2 possible buttons.
Check out this [link ](https://material-ui.com/demos/buttons/)to know how to create buttons.

The link can be done using the "to" attribute described [here](https://reacttraining.com/react-router/web/example/basic)
- [ ] A button that says "start voting" with a link to "/client"

- [ ] A button that says "display a voting graph" with a link to "/server"

Test your implementation here:
[![Edit material Ui basic example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/10q9r95ro7)

**Comment by erikstroby** [comment]
Vi tar dennnn
